ref: Aggregate dependencies in root Cargo.tom
OpenZeppelin/rust-contracts-stylus pull request #150
Opened 2024-06-22 14:29 UTC by developeruche

Moved all dependency importation to the root workspace `Cargo.toml` and referenced it at the crate level.

Resolves #144 

#### PR Checklist

- [ ] Tests
- [ ] Documentation

2024-06-22 15:08 UTC, alexfertel requested changes
Looks good! 🚀 

Let's keep `toml` and `hex-literal` in the crates that use them, otherwise this looks ready to merge.

2024-06-22 15:08 UTC, alexfertel commented on lib/crypto/Cargo.toml
> -hex-literal = "0.4.1"
Let's keep this one here.

2024-06-22 15:08 UTC, alexfertel commented on lib/e2e/Cargo.toml
> -toml = "0.8.13"
Let's keep this one here as well.

2024-06-22 15:21 UTC, alexfertel commented on lib/e2e/Cargo.toml
> -tokio = { version = "1.12.0", features = ["full", "process"] }
Let's keep this one as well, since it uses both `features = ["full", "process"]` and set it to only use `features = ["full"]` in the workspace root.

2024-06-23 10:58 UTC, alexfertel approved these changes
LGTM 🚀

2024-06-24 07:01 UTC, bidzyyys approved these changes
I like it, good job @developeruche 👏

2024-06-24 07:55 UTC, merged